# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://robeson1010.github.io/sMRItrans/"

git_url = "https://github.com/robeson1010/sMRItrans/tree/main/"

def custom_doc_links(name): return None
